# Set up NTP 
---
- name: Setup NTP 
  yum: name=ntp

- name: Configure NTP
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root

- name: Enable NTP
  service: name=ntpd state=started enabled=yes
